(add-to-list 'load-path "./")
(require 'thrift-socket-transport)
(require 'thrift-binary-protocol)

(setq transport (thrift-socket-transport "socketTrans"))
(thrift-transport-open transport)
(setq protocol (thrift-binary-protocol "BinaryProt" :transport transport))

;;(thrift-protocol-write-message-begin protocol "name" 1 2)
;;(thrift-protocol-write-i32 protocol -1)
;;(thrift-protocol-write-bool protocol nil)
;;(thrift-protocol-write-byte protocol 0)
;;(thrift-protocol-write-i16 protocol 0)
;;(thrift-protocol-write-i32 protocol 0)
;;(thrift-protocol-write-i64 protocol 0)
;;(thrift-protocol-write-string protocol "a")
;;(thrift-protocol-write-field-begin protocol "name" 1 2)
(thrift-protocol-write-map-begin protocol 1 2 3)

(setq recv (thrift-transport-read transport))
(message (format "recv: %s" recv))
(thrift-transport-close transport)
