;; Autogenerated by Thrift compiler (blablabla)

;; Do not edit unless you are sure that you know what you are doing

;; options string: blablabla

(require 'thrift)


(defclass thrift-client-calculator ()
  ((protocol :initarg :protocol
	     :document "Protocol to encode/decode and send/recv data.")
   (seqid    :initform 0
	     :document "The sequence ID of the client")
   (functions :initform (list
			 'ping	     '(thrift-client-calculator-ping-send
				       thrift-client-calculator-ping-recv)
			 'add	     '(thrift-client-calculator-add-send
				       thrift-client-calculator-add-recv)
			 'substracte '(thrift-client-calculator-substracte-send
				       thrift-client-calculator-substracte-recv)
			 'divide     '(thrift-client-calculator-divide-send
				       thrift-client-calculator-divide-recv))
	      :document "Functions supported by the client."))
  "Generated class for the calculator.")


;; todo: this one should be inherited from a parent class...
(defmethod thrift-client-call ((client thrift-client-calculator) function parameters callback)
  "Calls a thrift service of the client."
  (setq handler callback)
  ;; Build handler to call upon reception of the data of the reply
  (defun reply-data-handler ()
    (setq res (thrift-client-recv client))
    (funcall handler nil res))
  ;; Register the handler in the transport
  (oset (oref (oref client protocol) transport)
	on-data-received
	'reply-data-handler)
  ;; Write query to the protocol/transport with ad-hoc function
  (setq send-fun (car (plist-get (oref client functions) function)))
  (funcall send-fun client parameters))


;; todo: this one should be inherited from a parent class...
(defmethod thrift-client-recv ((client thrift-client-calculator))
  "Decode header of incoming reply and call associated decoder."
  (message "thrift-client-recv called")
  ;; Decode message header
  (setq header (thrift-protocol-readMessageBegin (oref client protocol)))
  (setq name (car header))
  (setq type (car (cdr header)))
  (setq seqid (car (cdr (cdr header))))
  ;; Decode and return reply content with ad-hoc decoder
  (setq recv-fun (car (cdr (plist-get (oref client functions) (intern name)))))
  (funcall recv-fun client))

;;; ping functions ;;;

(defmethod thrift-client-calculator-ping-send ((client thrift-client-calculator) parameters)
  "Send ping request."
  (thrift-protocol-writeMessageBegin (oref client protocol)
				     "ping"
				     thrift-cst-message-type-call
				     (oref client seqid))
  (thrift-protocol-writeStructBegin (oref client protocol) "ping_args")
  (thrift-protocol-writeFieldStop (oref client protocol))
  (thrift-protocol-writeStructEnd (oref client protocol))
  (thrift-protocol-writeMessageEnd (oref client protocol)))


(defmethod thrift-client-calculator-ping-recv ((client thrift-client-calculator))
  "Decode content of ping response."
  (thrift-protocol-readStructBegin (oref client protocol))
  (setq test t)
  (while test
    (setq res (thrift-protocol-readFieldBegin (oref client protocol)))
    (setq fname (car res))
    (setq ftype (car (cdr res)))
    (setq fid (car (cdr (cdr res))))
    (if (equal ftype 0)
	(setq test nil)
      (progn
	(thrift-protocol-skip (oref client protocol) ftype) ; todo: I haven't implemented this method yet...
	(thrift-protocol-readFieldEnd (oref client protocol))
	)))
  (thrift-protocol-readStructEnd (oref client protocol))
  nil)

;;; addfunctions ;;;
;todo

;;; substract functions ;;;
;todo

;;; divide functions ;;;
;todo

(provide 'thrift-client-calculator)
