;;
;; Autogenerated by Thrift compiler (1.0.0-dev)
;;
;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;
;; options string: el
;;

(require 'thrift)


(defmethod thrift-gen-tutorial-Calculator-write-Work (protocol work)
  "Write Work struct."
  (thrift-protocol-writeStructBegin protocol "Work")
  ;; parameter: num1
  (when (plist-get work :num1)
    (thrift-protocol-writeFieldBegin protocol
				     "num1"
				     (thrift-constant-type 'i32)
				     1)
    (thrift-protocol-writeI32 protocol (plist-get work :num1))
    (thrift-protocol-writeFieldEnd protocol))
  ;; parameter: num2
  (when (plist-get work :num2)
    (thrift-protocol-writeFieldBegin protocol
				     "num2"
				     (thrift-constant-type 'i32)
				     2)
    (thrift-protocol-writeI32 protocol (plist-get work :num2))
    (thrift-protocol-writeFieldEnd protocol))
  ;; parameter: op
  (when (plist-get work :op)
    (thrift-protocol-writeFieldBegin protocol
				     "op"
				     (thrift-constant-type 'i32)
				     3)
    (thrift-protocol-writeI32 protocol (plist-get work :op))
    (thrift-protocol-writeFieldEnd protocol))
  ;; parameter: comment
  (when (plist-get work :comment)
    (thrift-protocol-writeFieldBegin protocol
				     "comment"
				     (thrift-constant-type 'string)
				     4)
    (thrift-protocol-writeString protocol (plist-get work :comment))
    (thrift-protocol-writeFieldEnd protocol))
  (thrift-protocol-writeFieldStop protocol)
  (thrift-protocol-writeStructEnd protocol))


(defmethod thrift-gen-tutorial-Calculator-read-InvalidOperation (protocol)
  "Read InvalidOperation Exception."
  ;; Preset result
  (setq res-what nil)
  (setq res-why nil)
  ;; decode
  (thrift-protocol-readStructBegin protocol)
  (catch 'break
    (while t
      (setq r (thrift-protocol-readFieldBegin protocol))
      (setq fname (pop r))
      (setq ftype (pop r))
      (setq fid (pop r))
      (if (equal ftype (thrift-constant-type 'stop))
	  (throw 'break t))
      (cond ((equal fid 1)
	     (if (equal ftype (thrift-constant-type 'i32))
		 (setq res-what (thrift-protocol-readI32 protocol))
	       (thrift-protocol-skip protocol ftype)))
	    ((equal fid 2)
	     (if (equal ftype (thrift-constant-type 'string))
		 (setq res-string (thrift-protocol-readString protocol))
	       (thrift-protocol-skip protocol ftype)))
	    (t
	     (thrift-protocol-skip protocol ftype)))
      (thrift-protocol-readFieldEnd protocol)))
  (thrift-protocol-readStructEnd protocol)
  (list res-what res-why))


(provide 'thrift-gen-tutorial-ttypes)
