;;
;; Autogenerated by Thrift compiler (1.0.0-dev)
;;
;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;
;; options string: el
;;

(require 'thrift)
(require 'thrift-gen-tutorial-ttypes)
(require 'thrift-base-client)


(defclass thrift-gen-tutorial-Calculator (thrift-base-client)
  ((functions :initform (list
			 'ping       '(thrift-gen-tutorial-Calculator-write-ping-args
				       thrift-gen-tutorial-Calculator-read-ping-result)
			 'add        '(thrift-gen-tutorial-Calculator-write-add-args
				       thrift-gen-tutorial-Calculator-read-add-result)
			 'calculate  '(thrift-gen-tutorial-Calculator-write-calculate-args
				       thrift-gen-tutorial-Calculator-read-calculate-result))
	      :document "Helper functions for the various operations supported by the client."))
  "Generated class for the calculator.")



(defmethod thrift-gen-tutorial-Calculator-write-ping-args ((client thrift-gen-tutorial-Calculator) seqid args)
  "Send ping request."
  (setq protocol (oref client protocol))
  (thrift-protocol-writeMessageBegin protocol
				     "ping"
				     (thrift-constant-message-type 'call)
				     seqid)
  (thrift-protocol-writeStructBegin protocol "ping_args")
  (thrift-protocol-writeFieldStop protocol)
  (thrift-protocol-writeStructEnd protocol)
  (thrift-protocol-writeMessageEnd protocol))


(defmethod thrift-gen-tutorial-Calculator-read-ping-result ((client thrift-gen-tutorial-Calculator))
  "Decode content of ping response."
  (setq protocol (oref client protocol))
  (thrift-protocol-readStructBegin protocol)
  (catch 'break
    (while t
      (setq r (thrift-protocol-readFieldBegin protocol))
      (setq fname (pop r))
      (setq ftype (pop r))
      (setq fid (pop r))
    (if (equal ftype (thrift-constant-type 'stop))
	(throw 'break t)
      (thrift-protocol-skip protocol ftype))
    (thrift-protocol-readFieldEnd protocol)))
  (thrift-protocol-readStructEnd protocol)
  (list nil nil))


(defmethod thrift-gen-tutorial-Calculator-write-add-args ((client thrift-gen-tutorial-Calculator) seqid args)
  "Send add request."
  (setq protocol (oref client protocol))
  (thrift-protocol-writeMessageBegin protocol
				     "add"
				     (thrift-constant-message-type 'call)
				     seqid)
  (thrift-protocol-writeStructBegin protocol "add_args")
  ;; parameter: num2
  (when (plist-get args :num1)
    (thrift-protocol-writeFieldBegin protocol
				     "num1"
				     (thrift-constant-type 'i32)
				     1)
    (thrift-protocol-writeI32 protocol (plist-get args :num1))
    (thrift-protocol-writeFieldEnd protocol))
  ;; parameter: num2
  (when (plist-get args :num2)
    (thrift-protocol-writeFieldBegin protocol
				     "num2"
				     (thrift-constant-type 'i32)
				     2)
    (thrift-protocol-writeI32 protocol (plist-get args :num2))
    (thrift-protocol-writeFieldEnd protocol))
  (thrift-protocol-writeFieldStop protocol)
  (thrift-protocol-writeStructEnd protocol)
  (thrift-protocol-writeMessageEnd protocol))


(defmethod thrift-gen-tutorial-Calculator-read-add-result ((client thrift-gen-tutorial-Calculator))
  "Decode content of add response."
  ;; Preset result
  (setq res-error nil)
  (setq res-result nil)
  ;; decode
  (setq protocol (oref client protocol))
  (thrift-protocol-readStructBegin protocol)
  (catch 'break
    (while t
      (setq r (thrift-protocol-readFieldBegin protocol))
      (setq fname (pop r))
      (setq ftype (pop r))
      (setq fid (pop r))
      (if (equal ftype (thrift-constant-type 'stop))
	  (throw 'break t))
      (if (equal fid 0)
	  (if (equal ftype (thrift-constant-type 'i32))
	      (setq res-result (thrift-protocol-readI32 protocol))
	    (thrift-protocol-skip protocol ftype))
	(thrift-protocol-skip protocol ftype))
      (thrift-protocol-readFieldEnd protocol)))
  (thrift-protocol-readStructEnd protocol)
  (list res-error res-result))


(defmethod thrift-gen-tutorial-Calculator-write-calculate-args ((client thrift-gen-tutorial-Calculator) seqid args)
  "Send calculate request."
  (setq protocol (oref client protocol))
  (thrift-protocol-writeMessageBegin protocol
				     "calculate"
				     (thrift-constant-message-type 'call)
				     seqid)
  (thrift-protocol-writeStructBegin protocol "calculate_args")
  ;; parameter: logid
  (when (plist-get args :logid)
    (thrift-protocol-writeFieldBegin protocol
				     "logid"
				     (thrift-constant-type 'i32)
				     1)
    (thrift-protocol-writeI32 protocol (plist-get args :logid))
    (thrift-protocol-writeFieldEnd protocol))
  ;; parameter: w
  (when (plist-get args :w)
    (thrift-protocol-writeFieldBegin protocol
				     "w"
				     (thrift-constant-type 'struct)
				     2)
    (thrift-gen-tutorial-Calculator-write-Work protocol (plist-get args :w))
    (thrift-protocol-writeFieldEnd protocol))
  (thrift-protocol-writeFieldStop protocol)
  (thrift-protocol-writeStructEnd protocol)
  (thrift-protocol-writeMessageEnd protocol))


(defmethod thrift-gen-tutorial-Calculator-read-calculate-result ((client thrift-gen-tutorial-Calculator))
  "Decode content of calculate response."
  ;; Preset result
  (setq res-error nil)
  (setq res-result nil)
  ;; Decode
  (setq protocol (oref client protocol))
  (thrift-protocol-readStructBegin protocol)
  (catch 'break
    (while t
      (setq r (thrift-protocol-readFieldBegin protocol))
      (setq fname (pop r))
      (setq ftype (pop r))
      (setq fid (pop r))
      (if (equal ftype (thrift-constant-type 'stop))
	  (throw 'break t))
      (cond ((equal fid 0) ; Normal result received
	     (if (equal ftype (thrift-constant-type 'i32))
		 (setq res-result (thrift-protocol-readI32 protocol))
	       (thrift-protocol-skip protocol ftype)))
	    ((equal fid 1) ; InvalidOperation exception received
	     (if (equal ftype (thrift-constant-type 'struct))
		 (setq res-error (thrift-gen-tutorial-Calculator-read-InvalidOperation protocol))
	       (thrift-protocol-skip protocol ftype)))
	    (t
	     (thrift-protocol-skip protocol ftype)))
      (thrift-protocol-readFieldEnd protocol)))
  (thrift-protocol-readStructEnd protocol)
  (list res-error res-result))


(provide 'thrift-gen-tutorial-Calculator)
