;;
;; Autogenerated by Thrift Compiler (1.0.0-dev)
;;
;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;
;;  options string: el
;;

(require 'thrift)
(require 'thrift-gen-tutorial-types)

(setq INT32CONSTANT 9853)

(setq MAPCONSTANT '("hello" "world"
		    "goodnight" "moon"))

(provide 'thrift-gen-tutorial-constants)
